### ISSUE TITLE
repr of CamelCaseAliasEnum broken

### ISSUE THREAD

**Issue by jensens** [edutap-eu/edutap.wallet_google#12]
got i.e. `'Traceback (most recent call last):\n  File "/home/jensens/.vscode-oss/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_resolver.py", line 193, in _get_py_dictionary\n    attr = getattr(var, name)\n           ^^^^^^^^^^^^^^^^^^\n  File "/home/jensens/.pyenv/versions/3.12.6/lib/python3.12/enum.py", line 212, in __get__\n    return self.fget(instance)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/jensens/.pyenv/versions/3.12.6/lib/python3.12/enum.py", line 1290, in name\n    return self._name_\n           ^^^^^^^^^^^\nAttributeError: \'ViewUnlockRequirement\' object has no attribute \'_name_\'. Did you mean: \'name\'?\n'`

**Comment by jensens** [comment]
This is a problem with a normal Enum as well!
